### ISSUE TITLE
Endpoint returns 500 when following examples

### ISSUE THREAD

**Issue by Cesar199999** [gizatechxyz/giza-agents#47]
While following the examples in the `decision_tree.ipynb` and `linear_regression.ipynb` tutorials, I got the following error when calling `model.predict()` on the `GizaModel` object:

```
14:48:23.097 | ERROR   | giza_actions.model - An error occurred in predict: 500 Server Error: Internal Server Error for url: https://endpoint-cesar-[endpoint id].a.run.app/cairo_run

14:48:23.099 | ERROR   | giza_actions.model - Deployment predict error: Running the Cairo  programm failed
```

All previous cells ran successfully (transpilation, login, deployment, getting the workspace, etc.). Furthermore, calling `model.predict()` when `verifiable=False` seems to work, since I'm able to see the successful deployment in the dashboard.

I've tried to send the input myself using the `requests` library:

```
import requests
payload = " ".join(
    [
        serializer(create_tensor_from_array(
            input,
            "FP16x16"
        ))
    ]
)
response = requests.post("https://endpoint-cesar-[endpoint id].a.run.app/cairo_run", json=payload)
```
However, the same error persists.

**Comment by raphaelDkhn** [comment]
Thanks @Cesar199999 for reporting the issue. We are fixing this. It's an issue we are encountering with models running on our gcp. I let you know when this is fixed

**Comment by Gonmeso** [comment]
Errors have been improved in the platform and logs retrieval have been added on failed on #60
