### ISSUE TITLE
Add `np.flatten` when using ZKBoost

### ISSUE THREAD

**Issue by Gonmeso** [gizatechxyz/giza-agents#55]
ZKBoost expects a simple array of shape `(N, )`, but its common for users to give `(1, N)`.

* We should check the shape, if there are two shapes and rows is 1, we flatten, else we raise an error
* If shape is `(N, )` we keep going

changes should be done here: https://github.com/gizatechxyz/giza-agents/blob/main/giza/agents/model.py#L385

**Comment by EmmanuelAR** [comment]
Hey @Gonmeso can i work on this? I already work in actions-sdk, so will be pleasure to contribute in this too.
Let me know

**Comment by Josh-121** [comment]
Can get this done in few hrs, very familiar with working with such problems in python and can come up with an algorithm to detect the shape difference. Please assign if open, thanks

**Comment by vking45** [comment]
is this issue open for contribution ?
